const COMMON_REPORT_SECTIONS = [
  'executive_summary',
  'high_confidence_findings',
  'contradictions',
  'path_problems',
  'placeholders',
  'patch_candidates',
  'evidence_table',
  'known_good_comparison',
  'file_inventory',
  'risk_map',
  'validation_checklist',
  'agent_handoff',
];

const ANDROID_RECOVERY_PATTERNS = [
  /(^|\/)BoardConfig.*\.mk$/i,
  /(^|\/)AndroidProducts\.mk$/i,
  /(^|\/)device[^/]*\.mk$/i,
  /(^|\/)product[^/]*\.mk$/i,
  /(^|\/)orangefox_.*\.mk$/i,
  /(^|\/)twrp_.*\.mk$/i,
  /(^|\/)recovery\/root\/.*\.rc$/i,
  /(^|\/)root\/.*\.rc$/i,
  /(^|\/).*fstab.*$/i,
  /(^|\/).*key(master|mint).*$/i,
  /(^|\/).*gatekeeper.*$/i,
  /(^|\/).*decrypt.*$/i,
  /(^|\/).*touch.*$/i,
  /(^|\/).*display.*$/i,
  /(^|\/).*theme.*$/i,
  /(^|\/)vendor-files.*\.txt$/i,
  /(^|\/)proprietary-files.*\.txt$/i,
  /(^|\/)extract-files.*\.sh$/i,
];

const ANDROID_RECOVERY_REQUIRED_PATTERNS = [
  /(^|\/)BoardConfig.*\.mk$/i,
  /(^|\/)AndroidProducts\.mk$/i,
  /(^|\/).*fstab.*$/i,
];

const ANDROID_RECOVERY_VARIABLES = [
  'TARGET_BOARD_PLATFORM',
  'PRODUCT_PLATFORM',
  'PRODUCT_DEVICE',
  'PRODUCT_MODEL',
  'PRODUCT_NAME',
  'TARGET_DEVICE',
  'TARGET_OTA_ASSERT_DEVICE',
  'TARGET_BOOTLOADER_BOARD_NAME',
  'TARGET_RECOVERY_PIXEL_FORMAT',
  'BOARD_BOOT_HEADER_VERSION',
  'BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE',
  'BOARD_KERNEL_CMDLINE',
  'BOARD_KERNEL_BASE',
  'BOARD_KERNEL_PAGESIZE',
  'BOARD_MKBOOTIMG_ARGS',
  'BOARD_BOOTIMAGE_PARTITION_SIZE',
  'BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE',
  'BOARD_RECOVERYIMAGE_PARTITION_SIZE',
  'BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE',
  'TARGET_RECOVERY_FSTAB',
  'TW_THEME',
  'OF_SCREEN_H',
  'OF_SCREEN_W',
  'OF_TOUCH_*',
  'TW_INCLUDE_CRYPTO',
  'TW_INCLUDE_CRYPTO_FBE',
  'PRODUCT_COPY_FILES',
];

const ANDROID_VALIDATION_COMMANDS = [
  'find {{projectRoot}} -name BoardConfig.mk -o -name AndroidProducts.mk -o -name "*fstab*"',
  'grep -RIn "TARGET_BOARD_PLATFORM\\|PRODUCT_PLATFORM\\|PRODUCT_DEVICE\\|BOARD_RECOVERYIMAGE_PARTITION_SIZE\\|BOARD_BOOT_HEADER_VERSION" {{projectRoot}}',
  'grep -RIn "keymaster\\|keymint\\|gatekeeper\\|decrypt\\|vbmeta\\|avb\\|fstab" {{projectRoot}}',
];

const GAME_RUNTIME_PATTERNS = [
  /(^|\/)README(\..*)?$/i,
  /(^|\/).*config\.(ini|cfg|conf|json|toml|ya?ml)$/i,
  /(^|\/).*t7patch.*$/i,
  /(^|\/).*bo3.*$/i,
  /(^|\/).*blackops3.*$/i,
  /(^|\/)steam_appid\.txt$/i,
  /(^|\/).*dxvk.*$/i,
  /(^|\/).*vkd3d.*$/i,
  /(^|\/).*reshade.*$/i,
  /(^|\/).*specialk.*$/i,
  /(^|\/).*3dmigoto.*$/i,
  /(^|\/).*suwsf.*$/i,
  /(^|\/).*optiscaler.*$/i,
  /(^|\/)mods?(\/|$)/i,
  /(^|\/)plugins?(\/|$)/i,
  /(^|\/)players(\/|$)/i,
  /(^|\/)workshop(\/|$)/i,
];

const GAME_RUNTIME_VARIABLES = [
  'BlackOps3',
  'SteamAppId',
  'MaxFPS',
  'SmoothFramerate',
  'MaxFrameLatency',
  'BackbufferCount',
  'VideoMemory',
  'StreamMinResident',
  'RestrictGraphicsOptions',
  'com_maxfps',
  'WINEDLLOVERRIDES',
  'DXVK_*',
  'VKD3D_*',
  'VK_*',
];

const GAME_RUNTIME_VALIDATION_COMMANDS = [
  'find {{projectRoot}} -maxdepth 4 -type f | sort',
  'grep -RIn "BlackOps3\\|t7patch\\|BO3Enhanced\\|MaxFPS\\|SmoothFramerate\\|BackbufferCount\\|VideoMemory\\|StreamMinResident" {{projectRoot}}',
  'grep -RIn "dxvk\\|vkd3d\\|ReShade\\|SpecialK\\|3DMigoto\\|SUWSF\\|OptiScaler\\|VK_ICD_FILENAMES\\|VK_DRIVER_FILES" {{projectRoot}}',
  'grep -RIn "anti-cheat\\|anticheat\\|DRM\\|bypass\\|cheat\\|stealth\\|public match\\|ranked" {{projectRoot}}',
];

const PCGAMINGWIKI_PATTERNS = [
  ...GAME_RUNTIME_PATTERNS,
  /(^|\/).*pcgamingwiki.*$/i,
  /(^|\/).*compat.*\.(ini|cfg|conf|json|toml|ya?ml|md|txt)$/i,
  /(^|\/).*fix.*\.(ini|cfg|conf|json|toml|ya?ml|md|txt|reg|ps1|bat|cmd)$/i,
  /(^|\/).*proton.*$/i,
  /(^|\/).*wine.*$/i,
  /(^|\/).*steam.*$/i,
  /(^|\/).*x?dg.*$/i,
  /(^|\/).*registry.*$/i,
  /(^|\/).*save.*$/i,
];

const PCGAMINGWIKI_VARIABLES = [
  ...GAME_RUNTIME_VARIABLES,
  'GameTitle',
  'SteamAppId',
  'GOGID',
  'EpicID',
  'DRM',
  'Store',
  'ConfigPath',
  'SavePath',
  'CloudSync',
  'LaunchOptions',
  'API',
  'Middleware',
  'ControllerSupport',
  'Ports',
  'ProtonVersion',
  'WineVersion',
  'WinePrefix',
  'XDG_*',
];

const PCGAMINGWIKI_VALIDATION_COMMANDS = [
  ...GAME_RUNTIME_VALIDATION_COMMANDS,
  'grep -RIn "Configuration file\\|Save game\\|Cloud\\|XDG\\|compatdata\\|AppData\\|Documents\\|Saved Games" {{projectRoot}}',
  'grep -RIn "Availability\\|DRM\\|Steam\\|GOG\\|Epic\\|Microsoft Store\\|version differences\\|DLC" {{projectRoot}}',
  'grep -RIn "Video\\|FOV\\|ultrawide\\|widescreen\\|HDR\\|VSync\\|stutter\\|frame rate\\|FPS\\|DLSS\\|FSR\\|XeSS" {{projectRoot}}',
  'grep -RIn "Input\\|controller\\|Audio\\|Network\\|Multiplayer\\|Ports\\|VR support" {{projectRoot}}',
  'grep -RIn "API\\|Middleware\\|Direct3D\\|D3D11\\|D3D12\\|OpenGL\\|Vulkan\\|Bink\\|PhysX\\|Steamworks" {{projectRoot}}',
  'grep -RIn "Wine\\|Proton\\|Steam Deck\\|Linux\\|DXVK\\|VKD3D\\|Gamescope\\|gamemoderun\\|PROTON_LOG\\|WINEPREFIX" {{projectRoot}}',
];

const WIDESCREEN_FRAMEGEN_PATTERNS = [
  ...PCGAMINGWIKI_PATTERNS,
  /(^|\/).*flawless.*widescreen.*$/i,
  /(^|\/).*widescreen.*$/i,
  /(^|\/).*ultrawide.*$/i,
  /(^|\/).*frame[-_ ]?gen.*$/i,
  /(^|\/).*optiscaler.*$/i,
  /(^|\/).*optifg.*$/i,
  /(^|\/).*lsfg.*$/i,
  /(^|\/).*dlss.*$/i,
  /(^|\/).*fsr.*$/i,
  /(^|\/).*xess.*$/i,
];

const WIDESCREEN_FRAMEGEN_VARIABLES = [
  ...PCGAMINGWIKI_VARIABLES,
  'FlawlessWidescreen',
  'AspectRatio',
  'FOV',
  'HUDSafeArea',
  'WidescreenFix',
  'FrameGeneration',
  'FrameGenerationMultiplier',
  'OptiScaler',
  'OptiFG',
  'LSFG',
  'ENABLE_LSFG',
  'DLSSG',
  'FSR_FG',
  'XeFG',
  'Reflex',
  'AntiLag',
  'HUDFix',
];

const WIDESCREEN_FRAMEGEN_VALIDATION_COMMANDS = [
  ...PCGAMINGWIKI_VALIDATION_COMMANDS,
  'grep -RIn "Flawless Widescreen\\|WSGF\\|SUWSF\\|ultrawide\\|widescreen\\|Hor+\\|Vert-\\|FOV\\|aspect ratio\\|HUD\\|black bars\\|pillarbox\\|letterbox" {{projectRoot}}',
  'grep -RIn "frame generation\\|FrameGeneration\\|DLSSG\\|DLSS Frame Generation\\|FSR[-_ ]FG\\|FSR3\\|FSR 3\\|FSR4\\|XeFG\\|OptiScaler\\|OptiFG\\|Lossless Scaling\\|LSFG\\|ENABLE_LSFG" {{projectRoot}}',
  'grep -RIn "nvngx_dlssg\\|sl\\.dlss_g\\|sl\\.interposer\\|winmm\\.dll\\|dxgi\\.dll\\|version\\.dll\\|HUDless\\|HUD fix\\|Reflex\\|Anti-Lag" {{projectRoot}}',
  'grep -RIn "lsfg-vk\\|VK_LAYER\\|ENABLE_LSFG\\|DXVK\\|VKD3D\\|Gamescope\\|MangoHud\\|Steam Deck\\|Proton\\|Wine" {{projectRoot}}',
];

const GAME_EXE_PATCH_PATTERNS = [
  ...WIDESCREEN_FRAMEGEN_PATTERNS,
  /(^|\/).*(exe|binary|patch|rva|offset|aob|signature|x64dbg|ghidra|ida|disassembl).*$/i,
  /(^|\/).*\.patch\.(ini|cfg|conf|json|toml|ya?ml|md|txt)$/i,
  /(^|\/).*patch[-_ ]?manifest.*$/i,
  /(^|\/).*rollback.*$/i,
  /(^|\/).*backup.*$/i,
];

const GAME_EXE_PATCH_VARIABLES = [
  ...WIDESCREEN_FRAMEGEN_VARIABLES,
  'TargetExe',
  'TargetExePath',
  'PatchId',
  'PatchScope',
  'FileVersion',
  'ProductVersion',
  'SteamBuildId',
  'SHA256Before',
  'SHA256After',
  'CRC32Before',
  'PEMachine',
  'PETimestamp',
  'RVA',
  'FileOffset',
  'OriginalBytes',
  'PatchedBytes',
  'AOBSignature',
  'Symbol',
  'Disassembler',
  'BackupPath',
  'RollbackPlan',
  'LinuxPatchTarget',
  'ProtonPatchTarget',
  'WinePatchTarget',
  'LinuxValidation',
  'ProtonValidation',
  'DXVKValidation',
];

const GAME_EXE_PATCH_VALIDATION_COMMANDS = [
  ...WIDESCREEN_FRAMEGEN_VALIDATION_COMMANDS,
  'grep -RIn "TargetExe\\|PatchId\\|PatchScope\\|FileVersion\\|ProductVersion\\|SteamBuildId\\|SHA256Before\\|CRC32Before" {{projectRoot}}',
  'grep -RIn "RVA\\|FileOffset\\|OriginalBytes\\|PatchedBytes\\|AOBSignature\\|pattern scan\\|signature scan\\|x64dbg\\|Ghidra\\|IDA" {{projectRoot}}',
  'grep -RIn "BackupPath\\|RollbackPlan\\|restore\\|backup\\|offline only\\|private co-op\\|single-player" {{projectRoot}}',
  'grep -RIn "LinuxPatchTarget\\|ProtonPatchTarget\\|WinePatchTarget\\|Proton\\|Wine\\|DXVK\\|VKD3D\\|Gamescope\\|MangoHud\\|Steam Deck\\|SteamOS\\|WINEPREFIX\\|compatdata" {{projectRoot}}',
  'grep -RIn "DRM\\|anti-cheat\\|anticheat\\|bypass\\|public match\\|ranked\\|ownership verification" {{projectRoot}}',
];

const GPU_UPSCALE_FRAMEGEN_PATTERNS = [
  ...GAME_EXE_PATCH_PATTERNS,
  /(^|\/).*cupscale.*$/i,
  /(^|\/).*flowframes?.*$/i,
  /(^|\/).*upscal.*$/i,
  /(^|\/).*super[-_ ]?resolution.*$/i,
  /(^|\/).*interpolat.*$/i,
  /(^|\/).*frame[-_ ]?gen.*$/i,
  /(^|\/).*rife.*$/i,
  /(^|\/).*dain.*$/i,
  /(^|\/).*flavr.*$/i,
  /(^|\/).*esrgan.*$/i,
  /(^|\/).*swinir.*$/i,
  /(^|\/).*waifu2x.*$/i,
  /(^|\/).*real[-_ ]?cugan.*$/i,
  /(^|\/).*ncnn.*$/i,
  /(^|\/).*onnx.*$/i,
  /(^|\/).*tensorrt.*$/i,
  /(^|\/).*directml.*$/i,
  /(^|\/).*vapoursynth.*$/i,
  /(^|\/).*ffmpeg.*$/i,
  /(^|\/).*magick.*$/i,
  /(^|\/).*models?.*\.(json|txt|md)$/i,
];

const GPU_UPSCALE_FRAMEGEN_VARIABLES = [
  ...GAME_EXE_PATCH_VARIABLES,
  'RIFE',
  'DAIN',
  'FLAVR',
  'RealESRGAN',
  'ESRGAN',
  'SwinIR',
  'EDSR',
  'waifu2x',
  'RealCUGAN',
  'NCNN',
  'VulkanNCNN',
  'PyTorch',
  'CUDA',
  'TensorRT',
  'ONNXRuntime',
  'DirectML',
  'FFmpeg',
  'VapourSynth',
  'ImageMagick',
  'MagickNET',
  'ModelPath',
  'ModelLicense',
  'ModelHash',
  'ModelProvenance',
  'InterpolationFactor',
  'SceneChange',
  'Dedupe',
  'GPU_ID',
  'CUDA_VISIBLE_DEVICES',
];

const GPU_UPSCALE_FRAMEGEN_VALIDATION_COMMANDS = [
  ...GAME_EXE_PATCH_VALIDATION_COMMANDS,
  'grep -RIn "Cupscale\\|Flowframes\\|RIFE\\|DAIN\\|FLAVR\\|Real-ESRGAN\\|ESRGAN\\|SwinIR\\|EDSR\\|waifu2x\\|Real-CUGAN" {{projectRoot}}',
  'grep -RIn "NCNN\\|Vulkan\\|PyTorch\\|CUDA\\|TensorRT\\|ONNX Runtime\\|DirectML\\|FFmpeg\\|VapourSynth\\|Magick.NET\\|ImageMagick" {{projectRoot}}',
  'grep -RIn "\\.pth\\|\\.pt\\|\\.onnx\\|\\.safetensors\\|\\.bin\\|\\.param\\|\\.weights\\|model hash\\|license\\|provenance" {{projectRoot}}',
  'grep -RIn "fp16\\|half precision\\|optical flow\\|frame interpolation\\|frame generation\\|scene-change\\|dedup\\|GPU IDs" {{projectRoot}}',
];

const POWER_TDP_RUNTIME_PATTERNS = [
  ...GAME_RUNTIME_PATTERNS,
  /(^|\/).*autotdp.*$/i,
  /(^|\/).*hhd.*$/i,
  /(^|\/).*handheld.*$/i,
  /(^|\/).*tdp.*$/i,
  /(^|\/).*power.*$/i,
  /(^|\/).*battery.*$/i,
  /(^|\/).*ryzenadj.*$/i,
  /(^|\/).*acpi.*$/i,
  /(^|\/).*smu.*$/i,
  /(^|\/).*dmi.*$/i,
  /(^|\/)known_devices\.json$/i,
  /(^|\/)game_profiles\.json$/i,
  /(^|\/).*systemd.*$/i,
];

const POWER_TDP_RUNTIME_VARIABLES = [
  ...GAME_RUNTIME_VARIABLES,
  'RYZENADJ_EXEC',
  'MIN_TDP',
  'DEFAULT_TDP',
  'MAX_CPU_TDP',
  'STEP_TDP',
  'BATTERY_MAX_TDP',
  'MONITOR_INTERVAL',
  'STABLE_SAMPLE_COUNT',
  'RYZENADJ_DELAY',
  'PERFORMANCE_MODE',
  'SteamAppId',
  'SteamGameId',
  'STEAM_COMPAT_APP_ID',
  'WINEPREFIX',
  'POWER_MODE',
  'DEVICE_PROFILE',
  'DMI_*',
];

const POWER_TDP_RUNTIME_VALIDATION_COMMANDS = [
  'grep -RIn "ryzenadj\\|stapm-limit\\|fast-limit\\|slow-limit\\|acpi_call\\|/proc/acpi/call\\|SMU\\|ALIB" {{projectRoot}}',
  'grep -RIn "MIN_TDP\\|DEFAULT_TDP\\|MAX_CPU_TDP\\|BATTERY_MAX_TDP\\|STABLE_SAMPLE_COUNT\\|MONITOR_INTERVAL\\|RYZENADJ_DELAY" {{projectRoot}}',
  'grep -RIn "SteamAppId\\|SteamGameId\\|STEAM_COMPAT_APP_ID\\|executables\\|launcher_types\\|wine\\|proton" {{projectRoot}}',
  'grep -RIn "known_devices.json\\|/sys/devices/virtual/dmi\\|/proc/cpuinfo\\|/sys/class/power_supply" {{projectRoot}}',
  'grep -RIn "hhd.plugins\\|HHDPlugin\\|SimpleDeckyTDP\\|PowerControl\\|plugin_loader\\|power-profiles-daemon\\|tuned" {{projectRoot}}',
  'grep -RIn "systemctl\\|rm -rf\\|os.rename\\|/sys/firmware/acpi/platform_profile\\|charge_control_end_threshold" {{projectRoot}}',
];

const RENDER_ENHANCEMENT_VARIABLES = [
  'PresentHook',
  'ResizeBuffersHook',
  'SwapChainFormat',
  'TargetFrameTimeMs',
  'FramerateLimit',
  'WaitableSwapChain',
  'LowLatencyMode',
  'HDRMode',
  'HDRColorSpace',
  'TextureInjection',
  'ReplacementManifest',
  'APITranslation',
  'DXGI_*',
  'D3D11_*',
];

const RENDER_ENHANCEMENT_VALIDATION_COMMANDS = [
  'grep -RIn "IDXGISwapChain\\|Present1\\|Present\\|ResizeBuffers\\|CreateSwapChain\\|D3D11CreateDevice\\|DXGI_SWAP_CHAIN" {{projectRoot}}',
  'grep -RIn "TargetFrameTimeMs\\|FramerateLimit\\|WaitableSwapChain\\|LowLatencyMode\\|frametime\\|frame pacing\\|latency" {{projectRoot}}',
  'grep -RIn "TextureInjection\\|ReplacementManifest\\|DDS\\|BC7\\|mipmap\\|sRGB\\|CreateTexture2D\\|PSSetShaderResources" {{projectRoot}}',
  'grep -RIn "HDR10\\|scRGB\\|PQ\\|Rec2020\\|DXGI_COLOR_SPACE\\|SetHDRMetaData\\|R10G10B10A2" {{projectRoot}}',
  'grep -RIn "DXVK\\|VKD3D\\|D3D11On12\\|Vulkan\\|Wine\\|Proton\\|box64\\|Adreno\\|Turnip\\|Mesa\\|RM11Pro\\|Red Magic" {{projectRoot}}',
];

const AGENTIC_TOOLCHAIN_PATTERNS = [
  /(^|\/)(AGENTS|CLAUDE|WARP)\.md$/i,
  /(^|\/)README(\..*)?$/i,
  /(^|\/)SECURITY\.md$/i,
  /(^|\/)THIRD_PARTY_NOTICES\.md$/i,
  /(^|\/)package\.json$/i,
  /(^|\/)pyproject\.toml$/i,
  /(^|\/)uv\.lock$/i,
  /(^|\/).*settings.*\.(json|toml|ya?ml)$/i,
  /(^|\/).*hooks?(\.json|\.ya?ml|\.md|\.py|\.sh)?$/i,
  /(^|\/).*SKILL\.md$/i,
  /(^|\/)\.claude(\/|$)/i,
  /(^|\/)\.codex(\/|$)/i,
  /(^|\/)agents?(\/|$)/i,
  /(^|\/)commands?(\/|$)/i,
  /(^|\/)plugins?(\/|$)/i,
  /(^|\/)skills?(\/|$)/i,
  /(^|\/).*mcp.*$/i,
  /(^|\/).*memory.*$/i,
  /(^|\/).*context.*$/i,
  /(^|\/).*sourcemap.*$/i,
  /(^|\/)restored-src(\/|$)/i,
  /(^|\/).*cli\.js\.map$/i,
];

const AGENTIC_TOOLCHAIN_VARIABLES = [
  'ANTHROPIC_*',
  'OPENAI_*',
  'NVIDIA_NIM_*',
  'MODEL',
  'MODEL_*',
  'BASE_URL',
  'ANTHROPIC_BASE_URL',
  'OPENAI_BASE_URL',
  'CLAUDE_CODE_*',
  'CODEX_*',
  'FCC_*',
  'MCP_*',
  'HOOK_*',
  'PERMISSION_*',
  'ALLOW_*',
  'DENY_*',
  'MEMORY_*',
  'CONTEXT_*',
  'SUBAGENT_*',
  'WORKTREE_*',
];

const AGENTIC_TOOLCHAIN_VALIDATION_COMMANDS = [
  'find {{projectRoot}} -maxdepth 4 -type f | sort | head -300',
  'grep -RIn "AGENTS.md\\|CLAUDE.md\\|SKILL.md\\|hooks.json\\|PreToolUse\\|PostToolUse\\|UserPromptSubmit\\|Stop\\|SessionStart" {{projectRoot}}',
  'grep -RIn "ANTHROPIC_\\|OPENAI_\\|NVIDIA_NIM\\|MODEL\\|BASE_URL\\|Responses API\\|Anthropic Messages\\|provider" {{projectRoot}}',
  'grep -RIn "memory\\|context compact\\|compaction\\|transcript\\|evidence.jsonl\\|agent_handoff\\|subagent\\|worktree" {{projectRoot}}',
  'grep -RIn "sourcemap\\|cli.js.map\\|restored-src\\|decompile\\|NOASSERTION\\|all rights reserved\\|commercial terms\\|proprietary" {{projectRoot}}',
];

const SEMANTIC_POLICY_VALIDATION_COMMANDS = [
  ...AGENTIC_TOOLCHAIN_VALIDATION_COMMANDS,
  'grep -RIn "read-only\\|do not edit\\|patch away\\|approval\\|skip approvals\\|allow all\\|dangerously-skip-permissions" {{projectRoot}}',
  'grep -RIn "no adb\\|do not run adb\\|adb install\\|adb reboot\\|no network\\|git clone\\|curl\\|wget\\|gh api" {{projectRoot}}',
  'grep -RIn "reference-only\\|do not copy\\|attribution\\|NOASSERTION\\|stale agent\\|active agent" {{projectRoot}}',
];

const CLAUDE_CODE_MODERN_PATTERNS = [
  ...AGENTIC_TOOLCHAIN_PATTERNS,
  /(^|\/)(CLAUDE|AGENTS)\.md$/i,
  /(^|\/)\.claude\/settings(?:\.local|\.managed)?\.json$/i,
  /(^|\/)\.claude\/commands?(\/|$)/i,
  /(^|\/)\.claude\/agents?(\/|$)/i,
  /(^|\/)\.mcp\.json$/i,
  /(^|\/).*claude.*(?:settings|hooks|commands|agents|skills|mcp).*\.(md|json|toml|ya?ml)$/i,
  /(^|\/).*(session|transcript|handoff|background[-_ ]?agent).*\.(md|json|jsonl|txt)$/i,
];

const CLAUDE_CODE_MODERN_VARIABLES = [
  ...AGENTIC_TOOLCHAIN_VARIABLES,
  'CLAUDE_*',
  'CLAUDE_CODE_*',
  'CODEX_*',
  'MCP_*',
  'PLUGIN_*',
  'SKILL_*',
  'HOOK_*',
  'SUBAGENT_*',
  'APPROVAL_*',
  'SANDBOX_*',
  'PERMISSION_*',
];

const CLAUDE_CODE_MODERN_VALIDATION_COMMANDS = [
  ...SEMANTIC_POLICY_VALIDATION_COMMANDS,
  'grep -RIn "CLAUDE.md\\|AGENTS.md\\|settings.local.json\\|settings.managed.json\\|.claude/commands\\|.claude/agents" {{projectRoot}}',
  'grep -RIn "hooks\\|PreToolUse\\|PostToolUse\\|UserPromptSubmit\\|SessionStart\\|Stop\\|Notification\\|formatter\\|rm -rf\\|adb install" {{projectRoot}}',
  'grep -RIn "MCP\\|mcp server\\|plugin\\|skill\\|slash command\\|subagent\\|background agent\\|Agent SDK" {{projectRoot}}',
  'grep -RIn "modules_update/nebula_core\\|/data/adb/modules/nebula_core\\|active module\\|known-good frontier\\|generated artifact" {{projectRoot}}',
];

const KNOWN_GOOD_FRONTIER_PATTERNS = [
  /(^|\/)(result|counts|KNOWN_GOOD_LADDER|REGRESSION_POINT_MAP|ACTIVE_PHONE_PROOF_FORENSIC|REVERSA_REGRESSION_MEMORY|NEXT_ACTION_DECISION).*\.(md|tsv|json|txt|log)$/i,
  /(^|\/).*known[-_ ]?good.*$/i,
  /(^|\/).*frontier.*$/i,
  /(^|\/).*regression.*$/i,
  /(^|\/).*a1e.*$/i,
  /(^|\/).*a1[-_].*$/i,
  /(^|\/).*wayland.*$/i,
  /(^|\/).*xwayland.*$/i,
  /(^|\/).*gamescope.*$/i,
  /(^|\/).*vulkan.*$/i,
  /(^|\/).*counts\.tsv$/i,
];

const KNOWN_GOOD_FRONTIER_VARIABLES = [
  'NEBULA_R6_WAYLAND_WORKING_REAL_BUFFER_PASS',
  'NEBULA_R6_A1E_BASELINE_SIGBUS_CONFIRMED',
  'REGRESSION_BELOW_KNOWN_GOOD_FRONTIER',
  'real_buffer_commits',
  'real_commit_count',
  'vkGetMemoryFdKHR',
  'VKGETMEMORYFD_*',
  'VKGETMEMORYFD_FAILURE_COUNT',
  'GAMESCOPE_EXIT',
  'FINAL_XWAYLAND_RUNNER_INVOKED',
  'SELECTED_VULKAN_DEVICE',
  'XSERVER_READY',
  'xserver_ready',
  'GAMESCOPE_LIBPATH',
  'VK_ICD_FILENAMES',
  'VK_DRIVER_FILES',
];

const KNOWN_GOOD_FRONTIER_VALIDATION_COMMANDS = [
  'grep -RIn "NEBULA_R6_WAYLAND_WORKING_REAL_BUFFER_PASS\\|NEBULA_R6_A1E_BASELINE_SIGBUS_CONFIRMED\\|REGRESSION_BELOW_KNOWN_GOOD_FRONTIER" {{projectRoot}}',
  'grep -RIn "real_buffer_commits\\|real_commit_count\\|vkGetMemoryFdKHR\\|VKGETMEMORYFD" {{projectRoot}}',
  'grep -RIn "sidecar-14\\|sidecar-13\\|sidecar-06\\|force-composition\\|full-size AR24 parent xdg dmabuf\\|shm preload" {{projectRoot}}',
  'grep -RIn "GAMESCOPE_EXIT\\|FINAL_XWAYLAND_RUNNER_INVOKED\\|SELECTED_VULKAN_DEVICE\\|Xserver ready\\|xserver_ready\\|SIGBUS" {{projectRoot}}',
];

const DECODED_MEDIA_EVIDENCE_PATTERNS = [
  /(^|\/)decoded-media-manifest\.jsonl$/i,
];

const DECODED_MEDIA_EVIDENCE_VARIABLES = [
  'EVIDENCE:VIDEO_DECODED',
  'DRM:LEASE',
  'WAYLAND:LABWC',
  'PERF:FPS',
  'connector',
  'CRTC',
  'plane',
  'lease fd',
  'wlroots',
  'labwc',
  'KGSL',
  'GLES2',
];

const DECODED_MEDIA_EVIDENCE_VALIDATION_COMMANDS = [
  'grep -RIn "DRM:LEASE\\|lease fd received\\|wlroots DRM backend\\|labwc compositor\\|KGSL render device\\|PERF:FPS\\|FPS around" {{projectRoot}}',
];

const DROIDSPACES_DOCK_LEASE_PATTERNS = [
  /(^|\/)dock-lease-(command|result)\.schema\.json$/i,
  /(^|\/)tests\/fixtures\/dock-lease\/.*\.json$/i,
  /(^|\/).*dock[-_ ]?lease.*\.(json|jsonl|md|txt|log)$/i,
  /(^|\/).*command[-_ ]?plan.*\.(json|md|txt|log)$/i,
  /(^|\/).*drm[-_ ]?lease.*\.(json|md|txt|log)$/i,
];

const DROIDSPACES_DOCK_LEASE_VARIABLES = [
  'dock_drm_lease_external',
  'BLOCKED_NOT_READY',
  'DOCK_LEASE_COMMAND_PLAN_HOST_ONLY',
  'mutation_allowed_by_policy',
  'runtime_allowlists_modified',
  'app_allowlists_modified',
  'start_command_available',
  'dynamic_discovery_required',
  'TEST_ONLY',
  'SCM_RIGHTS',
  'stop_revoke',
  'rollback',
  'crash_gate',
];

const DROIDSPACES_DOCK_LEASE_VALIDATION_COMMANDS = [
  'grep -RIn "dock_drm_lease_external\\|dock lease\\|dock-lease\\|BLOCKED_NOT_READY" {{projectRoot}}',
  'grep -RIn "mutation_allowed_by_policy\\|execute\\|executed\\|mutation_performed\\|runtime_allowlists_modified\\|app_allowlists_modified\\|start_command_available" {{projectRoot}}',
  'grep -RIn "dynamic_discovery\\|TEST_ONLY\\|SCM_RIGHTS\\|stop_revoke\\|rollback\\|crash_gate\\|HOST_ONLY_FIXTURE" {{projectRoot}}',
];

const AGENTIC_GATEWAY_PATTERNS = [
  ...AGENTIC_TOOLCHAIN_PATTERNS,
  /(^|\/)(provider_catalog|provider_ids|registry|defaults|settings)\.(py|js|ts|json|toml|ya?ml)$/i,
  /(^|\/)(model_router|gateway_model_ids|model_catalog|codex_model_catalog)\.(py|js|ts|json|toml|ya?ml)$/i,
  /(^|\/)(request_pipeline|routes|dependencies|runtime|validation_log)\.(py|js|ts)$/i,
  /(^|\/)(claude|codex|common|entrypoints)\.(py|js|ts)$/i,
  /(^|\/)(admin|admin_static|admin_urls)(\/|$|.*\.(py|js|ts|html|css)$)/i,
  /(^|\/)(messaging|platforms?|transcript|voice|safe_diagnostics)(\/|$|.*\.(py|js|ts|md)$)/i,
  /(^|\/)(smoke|tests)(\/|$|.*\.(py|js|ts|md)$)/i,
  /(^|\/).*capabilit(y|ies).*\.(py|js|ts|json|md)$/i,
  /(^|\/).*features?.*\.(py|js|ts|json|md)$/i,
];

const AGENTIC_GATEWAY_VARIABLES = [
  ...AGENTIC_TOOLCHAIN_VARIABLES,
  'FCC_*',
  'ANTHROPIC_AUTH_TOKEN',
  'CLAUDE_CODE_*',
  'CODEX_*',
  'MODEL_OPUS',
  'MODEL_SONNET',
  'MODEL_HAIKU',
  'PROVIDER_*',
  '*_PROXY',
  '*_BASE_URL',
  'FCC_SMOKE_*',
  'MESSAGING_*',
  'VOICE_*',
];

const AGENTIC_GATEWAY_VALIDATION_COMMANDS = [
  ...AGENTIC_TOOLCHAIN_VALIDATION_COMMANDS,
  'grep -RIn "ProviderDescriptor\\|PROVIDER_CATALOG\\|SUPPORTED_PROVIDER_IDS\\|credential_env\\|capabilities" {{projectRoot}}',
  'grep -RIn "ModelRouter\\|resolve_model\\|MODEL_OPUS\\|MODEL_SONNET\\|MODEL_HAIKU\\|gateway_model" {{projectRoot}}',
  'grep -RIn "Anthropic Messages\\|OpenAI Responses\\|/v1/messages\\|/v1/responses\\|SSE\\|tool_use\\|thinking" {{projectRoot}}',
  'grep -RIn "fcc-claude\\|fcc-codex\\|ANTHROPIC_BASE_URL\\|model_provider\\|model_catalog_json\\|OPENAI_API_KEY" {{projectRoot}}',
  'grep -RIn "smoke_targets\\|FEATURE_INVENTORY\\|CAPABILITY_CONTRACTS\\|missing_env\\|product_failure" {{projectRoot}}',
  'grep -RIn "redact\\|safe_diagnostics\\|KEY\\|TOKEN\\|SECRET\\|AUTH" {{projectRoot}}',
];

const WINDOWS_SYSTEM_PATTERNS = [
  /(^|\/)README(\..*)?$/i,
  /(^|\/).*\.sln$/i,
  /(^|\/).*\.(csproj|vcxproj|vbproj|fsproj)$/i,
  /(^|\/).*\.(props|targets|filters)$/i,
  /(^|\/)Directory\.Build\.(props|targets)$/i,
  /(^|\/).*\.reg$/i,
  /(^|\/).*\.(ps1|psm1|psd1|bat|cmd)$/i,
  /(^|\/).*\.inf$/i,
  /(^|\/).*\.manifest$/i,
  /(^|\/).*\.(exe|dll|sys|ocx)$/i,
  /(^|\/).*(service|driver|installer|setup|registry|wix|msbuild|visualstudio|vs)\b.*$/i,
];

const WINDOWS_SYSTEM_VARIABLES = [
  'ServiceName',
  'DisplayName',
  'ServiceType',
  'StartType',
  'ImagePath',
  'DriverName',
  'DriverPackage',
  'TargetFramework',
  'PlatformToolset',
  'WindowsTargetPlatformVersion',
  'RuntimeIdentifier',
  'ConfigurationType',
  'OutDir',
  'TargetPath',
  'HKLM_*',
  'HKCU_*',
];

const WINDOWS_SYSTEM_VALIDATION_COMMANDS = [
  'find {{projectRoot}} -maxdepth 5 -type f | sort | head -300',
  'grep -RIn "ServiceBase\\|CreateService\\|New-Service\\|sc.exe\\|SERVICE_KERNEL_DRIVER\\|SERVICE_WIN32\\|CurrentControlSet\\\\\\\\Services" {{projectRoot}}',
  'grep -RIn "DriverEntry\\|KMDF\\|WDF\\|WDM\\|IoCreateDevice\\|IRP_MJ_\\|AddService\\|ClassGuid\\|UpperFilters\\|LowerFilters" {{projectRoot}}',
  'grep -RIn "HKLM\\\\\\\\\\|HKCU\\\\\\\\\\|HKEY_LOCAL_MACHINE\\|RegistryKey\\|reg add\\|reg.exe" {{projectRoot}}',
  'grep -RIn "PlatformToolset\\|WindowsTargetPlatformVersion\\|TargetFramework\\|RuntimeIdentifier\\|ProjectReference\\|Directory.Build" {{projectRoot}}',
  'grep -RIn "PE32\\|PE32+\\|IMAGE_FILE_MACHINE\\|Subsystem\\|requestedExecutionLevel\\|dumpbin\\|signtool\\|Authenticode" {{projectRoot}}',
];

export const PROFILES = {
  generic_source_tree: {
    id: 'generic_source_tree',
    label: 'Generic source tree',
    importantFilePatterns: [
      /(^|\/)README(\..*)?$/i,
      /(^|\/)package\.json$/i,
      /(^|\/)Makefile$/i,
      /(^|\/).*\.mk$/i,
      /(^|\/).*\.toml$/i,
      /(^|\/).*\.ya?ml$/i,
      /(^|\/).*\.json$/i,
    ],
    requiredFilePatterns: [],
    importantVariables: [],
    riskyLeftovers: ['sample', 'example', 'template', 'dummy', 'fake', 'placeholder'],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'duplicated definitions with different values',
      'referenced paths not present in the scanned tree',
      'TODO/FIXME markers in important files',
    ],
    validationCommands: [
      'find {{projectRoot}} -maxdepth 3 -type f | sort | head -200',
      'grep -RIn "TODO\\|FIXME\\|PLACEHOLDER\\|STUB" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  agentic_toolchain: {
    id: 'agentic_toolchain',
    label: 'Agentic CLI, skills, hooks, memory, and provider tooling',
    agenticToolchainProfile: true,
    importantFilePatterns: AGENTIC_TOOLCHAIN_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: AGENTIC_TOOLCHAIN_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'NOASSERTION',
      'all rights reserved',
      'commercial terms',
      'proprietary',
      'decompiled',
      'sourcemap',
      'restored-src',
      'dangerously-skip-permissions',
      'allow all',
    ],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'agent instruction files disagree about workflow or safety rules',
      'hook policy exists without permission boundaries',
      'memory or context injection is present without provenance notes',
      'provider routing variables conflict across Claude, Codex, and proxy launchers',
      'subagent or worktree isolation claims are not backed by scripts or docs',
      'restored, sourcemap, decompiled, or proprietary source appears in an import lane',
    ],
    validationCommands: AGENTIC_TOOLCHAIN_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  agentic_gateway: {
    id: 'agentic_gateway',
    label: 'Agentic provider gateway, client launcher, and smoke matrix',
    agenticToolchainProfile: true,
    agenticGatewayProfile: true,
    importantFilePatterns: AGENTIC_GATEWAY_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: AGENTIC_GATEWAY_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'NOASSERTION',
      'all rights reserved',
      'commercial terms',
      'proprietary',
      'decompiled',
      'sourcemap',
      'restored-src',
      'dangerously-skip-permissions',
      'allow all',
      'leak token',
      'raw shell',
    ],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'provider catalog, settings, and registry disagree',
      'Claude and Codex launchers strip or set conflicting credential variables',
      'Anthropic Messages and OpenAI Responses adapters diverge on streaming/tool semantics',
      'README features lack contract or smoke coverage owners',
      'messaging bridge logs user content or secrets without redaction',
      'admin UI exposes non-loopback control or unsafe config writes',
      'proprietary/source-map material leaks into reusable implementation lanes',
    ],
    validationCommands: AGENTIC_GATEWAY_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  semantic_policy: {
    id: 'semantic_policy',
    label: 'Semantic agent policy contradictions',
    extends: 'agentic_toolchain',
    agenticToolchainProfile: true,
    semanticPolicyProfile: true,
    importantFilePatterns: AGENTIC_TOOLCHAIN_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: AGENTIC_TOOLCHAIN_VARIABLES,
    riskyLeftovers: [
      'dangerously-skip-permissions',
      'skip approvals',
      'allow all',
      'approval_policy=never',
      'no adb',
      'adb install',
      'adb reboot',
      'no network',
      'git clone',
      'curl',
      'wget',
      'reference-only',
      'NOASSERTION',
      'stale agent',
    ],
    commonContradictions: [
      'read-only or no-edits instructions conflict with patch, commit, or push instructions',
      'approval-required policy conflicts with skip-approval or allow-all policy',
      'no device or no ADB policy conflicts with ADB, reboot, flashing, or device mutation commands',
      'no-network policy conflicts with git, curl, wget, or GitHub API actions',
      'reference-only or do-not-copy policy conflicts with vendored/copied source or missing attribution',
      'memory-reference-only policy conflicts with treating memory as authoritative instructions',
      'stale-agent cleanup policy conflicts with retained active-agent references',
    ],
    validationCommands: SEMANTIC_POLICY_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  claude_code_modern: {
    id: 'claude_code_modern',
    label: 'Modern Claude/Codex agent workflow surfaces',
    extends: 'semantic_policy',
    agenticToolchainProfile: true,
    semanticPolicyProfile: true,
    claudeCodeModernProfile: true,
    importantFilePatterns: CLAUDE_CODE_MODERN_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: CLAUDE_CODE_MODERN_VARIABLES,
    riskyLeftovers: [
      'dangerously-skip-permissions',
      'skip approvals',
      'allow all',
      'approval_policy=never',
      'rm -rf',
      'adb install',
      'adb reboot',
      'modules_update',
      'stale agent',
      'generated artifact',
      'source_authority=true',
      'sourcemap',
      'decompiled',
      'NOASSERTION',
      'all rights reserved',
    ],
    commonContradictions: [
      'read-only Claude/Codex tasks conflict with patch, commit, push, or install commands',
      'auto-approval policy conflicts with destructive command plans',
      'pending modules_update-first plans conflict with active-first known-good frontier rules',
      'generated transcripts or scan outputs are treated as source authority',
      'subagent handoff, MCP, plugin, hook, or skill surfaces lack scope boundaries',
    ],
    validationCommands: CLAUDE_CODE_MODERN_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  claude_code: {
    id: 'claude_code',
    label: 'Alias for modern Claude/Codex agent workflow surfaces',
    extends: 'claude_code_modern',
  },
  codex_agent: {
    id: 'codex_agent',
    label: 'Alias for modern Claude/Codex agent workflow surfaces',
    extends: 'claude_code_modern',
  },
  agent_workflow: {
    id: 'agent_workflow',
    label: 'Alias for modern Claude/Codex agent workflow surfaces',
    extends: 'claude_code_modern',
  },
  ai_coding_surface: {
    id: 'ai_coding_surface',
    label: 'Alias for modern Claude/Codex agent workflow surfaces',
    extends: 'claude_code_modern',
  },
  claude_matrix: {
    id: 'claude_matrix',
    label: 'Alias for modern Claude/Codex agent workflow surfaces',
    extends: 'claude_code_modern',
  },
  windows_system: {
    id: 'windows_system',
    label: 'Windows services, drivers, registry, PE, and MSBuild',
    windowsProfile: true,
    importantFilePatterns: WINDOWS_SYSTEM_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: WINDOWS_SYSTEM_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'sample service',
      'test signing only',
      'disable driver signature enforcement',
      'uac bypass',
      'PatchGuard',
      'LSASS',
    ],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'service install scripts disagree with service source or manifest',
      'driver INF metadata disagrees with KMDF/WDM source assumptions',
      'registry paths or service ImagePath values are undocumented',
      'Visual Studio project files disagree on platform, toolset, SDK, or output type',
      'PE metadata or manifest claims are present without matching build output evidence',
      'code signing, test signing, or installer assumptions lack validation evidence',
    ],
    validationCommands: WINDOWS_SYSTEM_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  windows_compat: {
    id: 'windows_compat',
    label: 'Windows compatibility alias',
    extends: 'windows_system',
  },
  android_recovery: {
    id: 'android_recovery',
    label: 'Android recovery device tree',
    importantFilePatterns: ANDROID_RECOVERY_PATTERNS,
    requiredFilePatterns: ANDROID_RECOVERY_REQUIRED_PATTERNS,
    importantVariables: ANDROID_RECOVERY_VARIABLES,
    riskyLeftovers: [
      'RM10Pro',
      'RM10',
      'sm8750',
      'kalama',
      'lahaina',
      'kona',
      'taro',
      'pineapple',
      'waipio',
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
    ],
    expectedDirectoryPatterns: [
      /(^|\/)recovery\/root(\/|$)/i,
      /(^|\/)vendor(\/|$)/i,
      /(^|\/)proprietary(\/|$)/i,
    ],
    commonContradictions: [
      'TARGET_BOARD_PLATFORM mismatch',
      'PRODUCT_PLATFORM mismatch',
      'codename mismatch',
      'partition size mismatch',
      'recovery image size mismatch',
      'boot header version mismatch',
      'wrong SoC family leftovers',
      'init rc service binary missing',
      'fstab references partition or mount options not supported by known-good facts',
      'AVB/vbmeta assumptions conflict with observed device facts',
    ],
    validationCommands: ANDROID_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  orangefox: {
    id: 'orangefox',
    label: 'OrangeFox recovery tree',
    extends: 'android_recovery',
    importantFilePatterns: [
      ...ANDROID_RECOVERY_PATTERNS,
      /(^|\/).*orangefox.*$/i,
      /(^|\/)vendorsetup\.sh$/i,
    ],
    importantVariables: [
      ...ANDROID_RECOVERY_VARIABLES,
      'FOX_*',
      'OF_*',
      'TW_*',
    ],
    riskyLeftovers: ['twrp-only', 'oldfox', 'RM10Pro', 'sm8750', 'template', 'placeholder'],
    validationCommands: [
      ...ANDROID_VALIDATION_COMMANDS,
      'grep -RIn "FOX_\\|OF_\\|TW_" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  orangefox_sync_tool: {
    id: 'orangefox_sync_tool',
    label: 'OrangeFox sync and patch tool',
    importantFilePatterns: [
      /(^|\/)README(\..*)?$/i,
      /(^|\/)orangefox_sync\.sh$/i,
      /(^|\/)fox_.*manifest.*$/i,
      /(^|\/)patches\/.*\.(diff|patch|txt)$/i,
    ],
    requiredFilePatterns: [],
    importantVariables: [
      'TWRP_BRANCH',
      'TW_DEVICE_BRANCH',
      'DEVICE_BRANCH',
      'FOX_*',
      'OF_*',
      'TW_*',
    ],
    riskyLeftovers: ['TODO', 'FIXME', 'PLACEHOLDER', 'STUB', 'oldfox', 'deprecated'],
    expectedDirectoryPatterns: [],
    externalCheckoutPathReferences: true,
    commonContradictions: [
      'sync branch variables disagree',
      'patch target paths are undocumented',
      'required dependency clone list is ambiguous',
      'placeholder or stale branch notes remain in the sync script',
    ],
    validationCommands: [
      'find {{projectRoot}} -maxdepth 3 -type f | sort',
      'grep -RIn "TWRP_BRANCH\\|TW_DEVICE_BRANCH\\|DEVICE_BRANCH\\|vendor/twrp\\|system/vold\\|device/qcom" {{projectRoot}}',
      'grep -RIn "TODO\\|FIXME\\|PLACEHOLDER\\|STUB" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  twrp: {
    id: 'twrp',
    label: 'TWRP recovery tree',
    extends: 'android_recovery',
    importantFilePatterns: ANDROID_RECOVERY_PATTERNS,
    importantVariables: [
      ...ANDROID_RECOVERY_VARIABLES,
      'TW_*',
    ],
    riskyLeftovers: ['orangefox-only', 'RM10Pro', 'sm8750', 'template', 'placeholder'],
    validationCommands: [
      ...ANDROID_VALIDATION_COMMANDS,
      'grep -RIn "TW_" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  android_kernel: {
    id: 'android_kernel',
    label: 'Android kernel tree',
    importantFilePatterns: [
      /(^|\/)Makefile$/i,
      /(^|\/)Kconfig$/i,
      /(^|\/)arch\/arm64\/configs\/.*defconfig$/i,
      /(^|\/)arch\/arm64\/boot\/dts\/.*\.dtsi?$/i,
    ],
    importantVariables: ['CONFIG_*', 'ARCH', 'CROSS_COMPILE', 'KERNELRELEASE'],
    riskyLeftovers: ['TODO', 'FIXME', 'PLACEHOLDER', 'STUB', 'deprecated'],
    expectedDirectoryPatterns: [/^arch\/arm64\//i, /^drivers\//i],
    commonContradictions: [
      'defconfig enables feature but driver path is absent',
      'DTS compatible strings conflict with target SoC',
    ],
    validationCommands: [
      'find {{projectRoot}} -path "*/arch/arm64/configs/*defconfig" -o -path "*/arch/arm64/boot/dts/*"',
      'grep -RIn "CONFIG_\\|compatible =" {{projectRoot}}/arch {{projectRoot}}/drivers',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  kernel: {
    id: 'kernel',
    label: 'Kernel tree alias',
    extends: 'android_kernel',
  },
  gki_kernel: {
    id: 'gki_kernel',
    label: 'GKI kernel tree',
    extends: 'android_kernel',
    importantFilePatterns: [
      /(^|\/)BUILD\.bazel$/i,
      /(^|\/)build\.config.*$/i,
      /(^|\/)common\/.*$/i,
      /(^|\/)modules\.load.*$/i,
    ],
    importantVariables: ['CONFIG_*', 'KMI_*', 'ABI_*'],
    riskyLeftovers: ['non-gki', 'vendor hack', 'TODO', 'FIXME'],
    validationCommands: [
      'find {{projectRoot}} -name "build.config*" -o -name "modules.load*" -o -name "abi_*"',
      'grep -RIn "KMI\\|ABI\\|CONFIG_" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  userspace_graphics: {
    id: 'userspace_graphics',
    label: 'Userspace graphics stack',
    importantFilePatterns: [
      /(^|\/)meson\.build$/i,
      /(^|\/)CMakeLists\.txt$/i,
      /(^|\/).*wayland.*$/i,
      /(^|\/).*xwayland.*$/i,
      /(^|\/).*glx.*$/i,
      /(^|\/).*egl.*$/i,
      /(^|\/).*vulkan.*$/i,
      /(^|\/).*drm.*$/i,
    ],
    importantVariables: ['LD_LIBRARY_PATH', 'VK_*', 'MESA_*', 'DISPLAY', 'WAYLAND_DISPLAY', 'XDG_RUNTIME_DIR'],
    riskyLeftovers: ['llvmpipe', 'swrast', 'software', 'stub', 'placeholder'],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'GLX/EGL configuration references libraries not present',
      'Wayland socket variables disagree across launch scripts',
      'software renderer fallback present in hardware-rendering lane',
    ],
    validationCommands: [
      'grep -RIn "GLX\\|EGL\\|Vulkan\\|VK_\\|LD_LIBRARY_PATH\\|WAYLAND_DISPLAY\\|DISPLAY" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  linux_container: {
    id: 'linux_container',
    label: 'Linux container runtime',
    importantFilePatterns: [
      /(^|\/)Dockerfile$/i,
      /(^|\/).*container.*$/i,
      /(^|\/).*rootfs.*$/i,
      /(^|\/).*chroot.*$/i,
      /(^|\/).*proot.*$/i,
      /(^|\/).*systemd.*$/i,
    ],
    importantVariables: ['PATH', 'LD_LIBRARY_PATH', 'HOME', 'USER', 'XDG_RUNTIME_DIR'],
    riskyLeftovers: ['host-only', 'placeholder', 'fake', 'stub'],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'host path leaked into container config',
      'rootfs path referenced but absent',
      'service binary referenced but absent',
    ],
    validationCommands: [
      'grep -RIn "rootfs\\|chroot\\|proot\\|LD_LIBRARY_PATH\\|XDG_RUNTIME_DIR" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  gamescope: {
    id: 'gamescope',
    label: 'Gamescope / wlroots graphics stack',
    extends: 'userspace_graphics',
    importantFilePatterns: [
      /(^|\/).*gamescope.*$/i,
      /(^|\/).*wlroots.*$/i,
      /(^|\/).*xwayland.*$/i,
      /(^|\/).*wayland.*$/i,
      /(^|\/).*drm.*$/i,
      /(^|\/).*xkb.*$/i,
    ],
    importantVariables: ['GAMESCOPE_*', 'WAYLAND_DISPLAY', 'DISPLAY', 'XWAYLAND_*', 'XKB_*', 'LD_LIBRARY_PATH'],
    riskyLeftovers: ['swrast', 'llvmpipe', 'placeholder', 'stub', 'drm lease'],
    validationCommands: [
      'grep -RIn "gamescope\\|wlroots\\|Xwayland\\|GLX\\|xkb\\|WAYLAND_DISPLAY\\|DISPLAY" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  child_libpath: {
    id: 'child_libpath',
    label: 'Nebula child, bridge, Gamescope, and loader libpath split',
    extends: 'userspace_graphics',
    runtimeProfile: true,
    nebulaRuntimeProfile: true,
    importantFilePatterns: [
      /(^|\/).*libpaths?.*$/i,
      /(^|\/).*env.*$/i,
      /(^|\/).*result.*$/i,
      /(^|\/).*gamescope.*$/i,
      /(^|\/).*bridge.*$/i,
      /(^|\/).*xwayland.*$/i,
      /(^|\/).*vulkan.*$/i,
      /(^|\/).*icd.*$/i,
    ],
    importantVariables: [
      'CHILD_LIBPATH',
      'GAMESCOPE_LIBPATH',
      'BRIDGE_LIBPATH',
      'XWAYLAND_LIBPATH',
      'FASTTEST02_LIBPATH',
      'LD_LIBRARY_PATH',
      'MESA_*',
      'GALLIUM_DRIVER',
      'FD_FORCE_KGSL',
      'LIBGL_ALWAYS_SOFTWARE',
      'VK_ICD_FILENAMES',
      'VK_DRIVER_FILES',
      'SELECTED_VULKAN_DEVICE',
      'VKGETMEMORYFD_*',
      'FINAL_XWAYLAND_*',
      'GAMESCOPE_EXIT',
    ],
    riskyLeftovers: [
      'mixed libpath',
      'imagefs-first',
      'swrast',
      'llvmpipe',
      'software renderer',
      'NOT_FOUND',
      'GAMESCOPE_EXIT=135',
    ],
    commonContradictions: [
      'Gamescope libpath order changed while testing GPU export env',
      'child software GL path leaked into Gamescope hardware path',
      'bridge library path overrides Vulkan loader or ICD ownership',
      'A1 export run exits before Xwayland or Vulkan device selection',
    ],
    validationCommands: [
      'grep -RIn "GAMESCOPE_LIBPATH\\|CHILD_LIBPATH\\|BRIDGE_LIBPATH\\|XWAYLAND_LIBPATH\\|FASTTEST02_LIBPATH" {{projectRoot}}',
      'grep -RIn "MESA_LOADER_DRIVER_OVERRIDE\\|GALLIUM_DRIVER\\|FD_FORCE_KGSL\\|LIBGL_ALWAYS_SOFTWARE\\|VK_ICD_FILENAMES\\|VK_DRIVER_FILES" {{projectRoot}}',
      'grep -RIn "GAMESCOPE_EXIT\\|FINAL_XWAYLAND_RUNNER_INVOKED\\|SELECTED_VULKAN_DEVICE\\|VKGETMEMORYFD_FIRST_LINE" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  nebula_child_libpath: {
    id: 'nebula_child_libpath',
    label: 'Nebula child libpath alias',
    extends: 'child_libpath',
  },
  nebula_gamescope: {
    id: 'nebula_gamescope',
    label: 'Nebula Gamescope alias',
    extends: 'gamescope',
    nebulaRuntimeProfile: true,
  },
  nebula_vulkan_loader: {
    id: 'nebula_vulkan_loader',
    label: 'Nebula Vulkan loader alias',
    extends: 'vulkan_loader',
    nebulaRuntimeProfile: true,
  },
  known_good_frontier: {
    id: 'known_good_frontier',
    label: 'Known-good frontier regression guard',
    extends: 'userspace_graphics',
    knownGoodFrontierProfile: true,
    runtimeProfile: true,
    nebulaRuntimeProfile: true,
    importantFilePatterns: KNOWN_GOOD_FRONTIER_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: KNOWN_GOOD_FRONTIER_VARIABLES,
    riskyLeftovers: [
      'newer failed run',
      'status-only',
      'blocked_export',
      'blocked_real_buffer',
      'sidecar-13',
      'shm preload',
      'GLX skipped',
      'NOT_FOUND',
      'GAMESCOPE_EXIT=135',
    ],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'newer lower run treated as frontier despite older raw known-good proof',
      'status-only success claims lack raw logs or counters',
      'A1/A1E evidence exits before Xwayland/Vulkan export proof',
      'runtime patch suggestion appears before exact known-good harness replay',
    ],
    validationCommands: KNOWN_GOOD_FRONTIER_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  nebula_frontier_guard: {
    id: 'nebula_frontier_guard',
    label: 'Nebula known-good frontier guard alias',
    extends: 'known_good_frontier',
  },
  frontier_guard: {
    id: 'frontier_guard',
    label: 'Known-good frontier guard alias',
    extends: 'known_good_frontier',
  },
  decoded_media_evidence: {
    id: 'decoded_media_evidence',
    label: 'Decoded media evidence manifest',
    runtimeProfile: true,
    nebulaRuntimeProfile: true,
    decodedMediaEvidenceProfile: true,
    importantFilePatterns: DECODED_MEDIA_EVIDENCE_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: DECODED_MEDIA_EVIDENCE_VARIABLES,
    riskyLeftovers: [],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'decoded media proof is promoted without source manifest hash or frame/OCR artifact path',
      'FPS overlay is treated as standalone runtime-lane proof',
      'hard-coded DRM object IDs are replayed instead of rediscovered dynamically',
    ],
    validationCommands: DECODED_MEDIA_EVIDENCE_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  nebula_media_evidence: {
    id: 'nebula_media_evidence',
    label: 'Nebula decoded media evidence alias',
    extends: 'decoded_media_evidence',
  },
  telegram_media_evidence: {
    id: 'telegram_media_evidence',
    label: 'Telegram decoded media evidence alias',
    extends: 'decoded_media_evidence',
  },
  droidspaces_dock_lease: {
    id: 'droidspaces_dock_lease',
    label: 'DroidSpaces Dock lease proof guard',
    runtimeProfile: true,
    nebulaRuntimeProfile: true,
    dockLeaseProofProfile: true,
    importantFilePatterns: DROIDSPACES_DOCK_LEASE_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: DROIDSPACES_DOCK_LEASE_VARIABLES,
    riskyLeftovers: [
      'runtime_allowlists_modified=true',
      'app_allowlists_modified=true',
      'start_command_available=true',
      'mutation_allowed_by_policy=true',
      'execute=true',
      'executed=true',
      'mutation_performed=true',
    ],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'Dock lease host-only proof is promoted into a runtime start command',
      'runtime or app allowlists are modified before receiver smoke, TEST_ONLY, stop/revoke, rollback, and crash gates are proven',
      'manual connector, CRTC, plane, fd, or whole-card takeover is allowed instead of dynamic external-only discovery',
    ],
    validationCommands: DROIDSPACES_DOCK_LEASE_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  nebula_dock_schema: {
    id: 'nebula_dock_schema',
    label: 'Nebula Dock schema proof alias',
    extends: 'droidspaces_dock_lease',
  },
  dock_command_plan: {
    id: 'dock_command_plan',
    label: 'Dock command-plan proof alias',
    extends: 'droidspaces_dock_lease',
  },
  game_modding: {
    id: 'game_modding',
    label: 'Game modding runtime',
    runtimeProfile: true,
    importantFilePatterns: GAME_RUNTIME_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: GAME_RUNTIME_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'bypass',
      'anti-cheat',
      'anticheat',
      'Arxan',
      'public match',
      'ranked',
      'stealth',
    ],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'runtime target identity is ambiguous',
      'wrapper DLL chain is present but not documented',
      'graphics loader variables point at missing or incompatible drivers',
      'performance config values disagree across launch profiles',
      'security or exploit-mitigation notes are present without validation evidence',
      'anti-cheat, DRM, public-match, or ownership-evasion terms require a hard safety review',
    ],
    validationCommands: GAME_RUNTIME_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  pcgamingwiki_runtime: {
    id: 'pcgamingwiki_runtime',
    label: 'PCGamingWiki-style PC game compatibility evidence',
    runtimeProfile: true,
    pcgamingwikiProfile: true,
    importantFilePatterns: PCGAMINGWIKI_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: PCGAMINGWIKI_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'unverified fix',
      'outdated fix',
      'test signing only',
      'DRM bypass',
      'anti-cheat bypass',
      'public match',
      'ranked',
    ],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'game data paths differ across Windows, Linux, Proton, or XDG notes',
      'availability, store, DRM, or version-difference notes are undocumented',
      'video/display fix claims lack matching API, middleware, or runtime evidence',
      'input, audio, network, ports, or VR claims lack validation notes',
      'Wine/Proton/Linux fixes are mixed with native Windows assumptions',
      'fix notes include safety-boundary terms that require review',
    ],
    validationCommands: PCGAMINGWIKI_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  widescreen_framegen_runtime: {
    id: 'widescreen_framegen_runtime',
    label: 'Widescreen fixes and frame generation runtime',
    extends: 'pcgamingwiki_runtime',
    pcgamingwikiProfile: true,
    widescreenFramegenProfile: true,
    importantFilePatterns: WIDESCREEN_FRAMEGEN_PATTERNS,
    importantVariables: WIDESCREEN_FRAMEGEN_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'unverified fix',
      'outdated fix',
      'unsafe memory patch',
      'anti-cheat bypass',
      'public match',
      'ranked',
    ],
    commonContradictions: [
      'Flawless Widescreen or ultrawide fix target differs from game/runtime identity',
      'FOV, aspect ratio, or HUD fix claims lack platform-specific validation',
      'frame-generation runtime differs across Windows DLL/proxy and Linux Vulkan-layer paths',
      'DLSSG, FSR FG, XeFG, OptiScaler, OptiFG, LSFG, or Reflex/Anti-Lag settings disagree',
      'Linux/Proton frame-generation evidence is mixed with native Windows-only assumptions',
    ],
    validationCommands: WIDESCREEN_FRAMEGEN_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  game_exe_patch_runtime: {
    id: 'game_exe_patch_runtime',
    label: 'Offline game executable patch evidence',
    extends: 'widescreen_framegen_runtime',
    pcgamingwikiProfile: true,
    widescreenFramegenProfile: true,
    exePatchProfile: true,
    importantFilePatterns: GAME_EXE_PATCH_PATTERNS,
    importantVariables: GAME_EXE_PATCH_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'unverified patch',
      'unsafe memory patch',
      'DRM bypass',
      'anti-cheat bypass',
      'stealth injection',
      'public match',
      'ranked',
      'ownership verification',
    ],
    commonContradictions: [
      'patch manifest lacks target executable version or hash guard',
      'RVA, file offset, AOB signature, or symbol notes disagree',
      'original bytes, patched bytes, and rollback plan are incomplete',
      'Linux/Proton/Wine validation is missing for a Linux-targeted executable patch',
      'patch scope is not limited to offline, single-player, or private co-op use',
      'DRM, anti-cheat, public-match, or ownership-evasion terms require hard review',
    ],
    validationCommands: GAME_EXE_PATCH_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  gpu_upscale_framegen: {
    id: 'gpu_upscale_framegen',
    label: 'GPU upscaling and frame-generation evidence',
    extends: 'game_exe_patch_runtime',
    runtimeProfile: true,
    pcgamingwikiProfile: true,
    widescreenFramegenProfile: true,
    exePatchProfile: true,
    gpuUpscaleFramegenProfile: true,
    importantFilePatterns: GPU_UPSCALE_FRAMEGEN_PATTERNS,
    importantVariables: GPU_UPSCALE_FRAMEGEN_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'unknown license',
      'missing hash',
      'unverified CUDA',
      'unverified Proton',
      'unsafe memory patch',
      'DRM bypass',
      'anti-cheat bypass',
      'public match',
      'ranked',
    ],
    commonContradictions: [
      'model asset references lack license, provenance, or hash evidence',
      'CUDA or 5090 acceleration is claimed without nvidia-smi, torch.cuda, CUDA runtime, driver, and backend evidence',
      'Linux or Proton compatibility is claimed without runtime proof',
      'EXE patch notes lack original/patched hashes, reversible patch plan, backup, version, offset/signature, patch source, or legal note',
      'generated scan/training/eval artifacts are being treated as source authority',
    ],
    validationCommands: GPU_UPSCALE_FRAMEGEN_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  upscale_runtime: {
    id: 'upscale_runtime',
    label: 'GPU upscaling runtime alias',
    extends: 'gpu_upscale_framegen',
  },
  framegen_runtime: {
    id: 'framegen_runtime',
    label: 'Frame-generation runtime alias',
    extends: 'gpu_upscale_framegen',
  },
  game_upscale: {
    id: 'game_upscale',
    label: 'Game upscaling runtime alias',
    extends: 'gpu_upscale_framegen',
  },
  flowframes: {
    id: 'flowframes',
    label: 'Flowframes reference alias',
    extends: 'gpu_upscale_framegen',
  },
  cupscale: {
    id: 'cupscale',
    label: 'Cupscale reference alias',
    extends: 'gpu_upscale_framegen',
  },
  power_tdp_runtime: {
    id: 'power_tdp_runtime',
    label: 'Power/TDP runtime and handheld daemon research',
    runtimeProfile: true,
    powerTdpRuntimeProfile: true,
    importantFilePatterns: POWER_TDP_RUNTIME_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: POWER_TDP_RUNTIME_VARIABLES,
    riskyLeftovers: [
      'ryzenadj',
      'stapm-limit',
      'fast-limit',
      'slow-limit',
      'acpi_call',
      '/proc/acpi/call',
      'SMU',
      'ALIB',
      'systemctl start',
      'systemctl stop',
      'systemctl enable',
      'systemctl restart',
      'rm -rf',
      'os.rename',
      'plugin_loader',
      'runtime proof missing',
    ],
    commonContradictions: [
      'power backend is detected but no runtime proof exists',
      'TDP, ACPI, SMU, service, or plugin mutation is present without explicit approval gates',
      'game profile identity is ambiguous between Steam AppID, executable, Wine, and Proton sources',
      'battery cap or performance mode is declared without device profile evidence',
      'handheld daemon or Decky plugin conflict handling is present without a controlled-test plan',
    ],
    validationCommands: POWER_TDP_RUNTIME_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  autotdp: {
    id: 'autotdp',
    label: 'AutoTDP research alias',
    extends: 'power_tdp_runtime',
  },
  hhd_autotdp: {
    id: 'hhd_autotdp',
    label: 'HHD AutoTDP research alias',
    extends: 'power_tdp_runtime',
  },
  tdp_control: {
    id: 'tdp_control',
    label: 'TDP control research alias',
    extends: 'power_tdp_runtime',
  },
  handheld_daemon: {
    id: 'handheld_daemon',
    label: 'Handheld daemon research alias',
    extends: 'power_tdp_runtime',
  },
  game_power_profile: {
    id: 'game_power_profile',
    label: 'Game power profile research alias',
    extends: 'power_tdp_runtime',
  },
  battery_perf_profile: {
    id: 'battery_perf_profile',
    label: 'Battery/performance profile research alias',
    extends: 'power_tdp_runtime',
  },
  graphics_wrapper: {
    id: 'graphics_wrapper',
    label: 'Graphics wrapper and injection chain',
    extends: 'game_modding',
    importantFilePatterns: [
      ...GAME_RUNTIME_PATTERNS,
      /(^|\/).*d3d.*$/i,
      /(^|\/).*dxgi.*$/i,
      /(^|\/).*vulkan.*$/i,
      /(^|\/).*shader.*$/i,
    ],
    importantVariables: [
      ...GAME_RUNTIME_VARIABLES,
      'DXVK_*',
      'VKD3D_*',
      'MESA_*',
      'PROTON_*',
      'WINEDLLOVERRIDES',
    ],
    riskyLeftovers: ['stub', 'placeholder', 'software renderer', 'swrast', 'llvmpipe', 'bypass'],
    validationCommands: [
      'grep -RIn "dxvk\\|vkd3d\\|d3d11\\|dxgi\\|dinput8\\|winmm\\|version.dll\\|ReShade\\|SpecialK\\|3DMigoto\\|SUWSF\\|OptiScaler" {{projectRoot}}',
      'grep -RIn "WINEDLLOVERRIDES\\|VK_ICD_FILENAMES\\|VK_DRIVER_FILES\\|VK_LOADER_DEBUG\\|MESA_\\|PROTON_" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  vulkan_loader: {
    id: 'vulkan_loader',
    label: 'Vulkan loader and ICD runtime',
    runtimeProfile: true,
    importantFilePatterns: [
      /(^|\/).*vulkan.*$/i,
      /(^|\/).*icd.*\.json$/i,
      /(^|\/).*dxvk.*$/i,
      /(^|\/).*vkd3d.*$/i,
      /(^|\/).*loader.*$/i,
      /(^|\/).*gpu.*$/i,
      /(^|\/).*mesa.*$/i,
    ],
    requiredFilePatterns: [],
    importantVariables: ['VK_ICD_FILENAMES', 'VK_DRIVER_FILES', 'VK_LOADER_DEBUG', 'VK_INSTANCE_LAYERS', 'MESA_*', 'DXVK_*', 'VKD3D_*'],
    riskyLeftovers: ['llvmpipe', 'swrast', 'software', 'ERROR_INCOMPATIBLE_DRIVER', 'placeholder', 'stub'],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'ICD JSON references a missing library',
      'loader debug output reports incompatible driver negotiation',
      'runtime variables select different Vulkan drivers',
      'software renderer fallback appears in a hardware-rendering lane',
    ],
    validationCommands: [
      'grep -RIn "VK_ICD_FILENAMES\\|VK_DRIVER_FILES\\|VK_LOADER_DEBUG\\|VK_INSTANCE_LAYERS\\|vk_icdNegotiateLoaderICDInterfaceVersion\\|ERROR_INCOMPATIBLE_DRIVER\\|ICD.library_path\\|api_version" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  bo3_zombies_diagnostics: {
    id: 'bo3_zombies_diagnostics',
    label: 'Black Ops 3 Zombies diagnostics',
    extends: 'game_modding',
    importantFilePatterns: [
      ...GAME_RUNTIME_PATTERNS,
      /(^|\/).*zombies?.*$/i,
      /(^|\/).*workshop.*$/i,
      /(^|\/).*t7.*$/i,
      /(^|\/).*players\/config\.ini$/i,
    ],
    importantVariables: [
      ...GAME_RUNTIME_VARIABLES,
      'network_password',
      'lobby_password',
      'friends_only',
    ],
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'anti-cheat',
      'anticheat',
      'Arxan',
      'bypass',
      'cheat menu',
      'trainer',
      'stealth injection',
      'public match',
      'ranked',
      'unlock all',
      'ban evasion',
      'ownership verification',
    ],
    commonContradictions: [
      'BO3 runtime identity or Steam AppID is ambiguous',
      'Zombies/private co-op security settings are present without validation notes',
      'performance config values disagree across profiles',
      'wrapper DLL chain is present without explicit load-order evidence',
      'anti-cheat, DRM, public-match, or ownership-evasion terms require a hard safety review',
    ],
    validationCommands: GAME_RUNTIME_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  render_enhancement_plugin: {
    id: 'render_enhancement_plugin',
    label: 'Render enhancement plugin',
    extends: 'graphics_wrapper',
    importantFilePatterns: [
      ...GAME_RUNTIME_PATTERNS,
      /(^|\/).*specialk.*$/i,
      /(^|\/).*render.*$/i,
      /(^|\/).*swapchain.*$/i,
      /(^|\/).*frame.*$/i,
      /(^|\/).*hdr.*$/i,
      /(^|\/).*texture.*$/i,
      /(^|\/).*manifest.*\.(json|toml|ya?ml|ini|cfg|conf|txt)$/i,
      /(^|\/).*plugins?(\/|$)/i,
    ],
    importantVariables: [
      ...GAME_RUNTIME_VARIABLES,
      ...RENDER_ENHANCEMENT_VARIABLES,
    ],
    riskyLeftovers: ['stub', 'placeholder', 'software renderer', 'swrast', 'llvmpipe', 'bypass', 'stealth'],
    commonContradictions: [
      'render hook target is ambiguous',
      'frame limiter target conflicts with game config',
      'texture replacement manifest is referenced but absent',
      'HDR color space or swapchain format is declared without validation evidence',
      'API translation path differs across Windows, Wine, Proton, or mobile Linux profiles',
    ],
    validationCommands: RENDER_ENHANCEMENT_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  rm11pro_gaming_runtime: {
    id: 'rm11pro_gaming_runtime',
    label: 'Red Magic 11 Pro gaming runtime',
    extends: 'render_enhancement_plugin',
    importantFilePatterns: [
      ...GAME_RUNTIME_PATTERNS,
      /(^|\/).*rm11pro.*$/i,
      /(^|\/).*red[-_ ]?magic.*$/i,
      /(^|\/).*adreno.*$/i,
      /(^|\/).*turnip.*$/i,
      /(^|\/).*mesa.*$/i,
      /(^|\/).*box64.*$/i,
      /(^|\/).*wine.*$/i,
      /(^|\/).*proot.*$/i,
      /(^|\/).*termux.*$/i,
      /(^|\/).*winlator.*$/i,
    ],
    importantVariables: [
      ...GAME_RUNTIME_VARIABLES,
      ...RENDER_ENHANCEMENT_VARIABLES,
      'MESA_*',
      'TU_*',
      'BOX64_*',
      'WINE_*',
      'PROOT_*',
      'TERMUX_*',
      'VK_DRIVER_FILES',
      'VK_ICD_FILENAMES',
    ],
    riskyLeftovers: ['llvmpipe', 'swrast', 'software renderer', 'placeholder', 'stub', 'host-only'],
    commonContradictions: [
      'RM11Pro runtime identity is ambiguous',
      'Adreno or Turnip driver selection conflicts with Vulkan loader evidence',
      'box64, Wine, or container variables disagree across launch profiles',
      'desktop render settings are reused without mobile validation evidence',
    ],
    validationCommands: [
      ...RENDER_ENHANCEMENT_VALIDATION_COMMANDS,
      'grep -RIn "RM11Pro\\|Red Magic\\|Adreno\\|Turnip\\|Mesa\\|box64\\|Wine\\|proot\\|Termux\\|Winlator\\|VK_DRIVER_FILES\\|VK_ICD_FILENAMES" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
};

export function getProfile(profileId = 'generic_source_tree') {
  return resolveProfile(profileId);
}

function resolveProfile(profileId, seen = new Set()) {
  const profile = PROFILES[profileId];
  if (!profile) {
    const known = Object.keys(PROFILES).sort().join(', ');
    throw new Error(`Unknown scan profile "${profileId}". Known profiles: ${known}`);
  }
  if (seen.has(profileId)) {
    throw new Error(`Profile inheritance cycle detected at "${profileId}".`);
  }

  if (!profile.extends) {
    return profile;
  }

  const parent = resolveProfile(profile.extends, new Set([...seen, profileId]));
  return {
    ...parent,
    ...profile,
    importantFilePatterns: profile.importantFilePatterns ?? parent.importantFilePatterns,
    requiredFilePatterns: profile.requiredFilePatterns ?? parent.requiredFilePatterns,
    importantVariables: profile.importantVariables ?? parent.importantVariables,
    riskyLeftovers: profile.riskyLeftovers ?? parent.riskyLeftovers,
    validationCommands: profile.validationCommands ?? parent.validationCommands,
    reportSections: profile.reportSections ?? parent.reportSections,
  };
}

export function listProfiles() {
  return Object.values(PROFILES).map(profile => ({
    id: profile.id,
    label: profile.label,
  }));
}
