const COMMON_REPORT_SECTIONS = [
  'executive_summary',
  'high_confidence_findings',
  'contradictions',
  'path_problems',
  'placeholders',
  'patch_candidates',
  'evidence_table',
  'known_good_comparison',
  'file_inventory',
  'risk_map',
  'validation_checklist',
  'agent_handoff',
];

const ANDROID_RECOVERY_PATTERNS = [
  /(^|\/)BoardConfig.*\.mk$/i,
  /(^|\/)AndroidProducts\.mk$/i,
  /(^|\/)device[^/]*\.mk$/i,
  /(^|\/)product[^/]*\.mk$/i,
  /(^|\/)orangefox_.*\.mk$/i,
  /(^|\/)twrp_.*\.mk$/i,
  /(^|\/)recovery\/root\/.*\.rc$/i,
  /(^|\/)root\/.*\.rc$/i,
  /(^|\/).*fstab.*$/i,
  /(^|\/).*key(master|mint).*$/i,
  /(^|\/).*gatekeeper.*$/i,
  /(^|\/).*decrypt.*$/i,
  /(^|\/).*touch.*$/i,
  /(^|\/).*display.*$/i,
  /(^|\/).*theme.*$/i,
  /(^|\/)vendor-files.*\.txt$/i,
  /(^|\/)proprietary-files.*\.txt$/i,
  /(^|\/)extract-files.*\.sh$/i,
];

const ANDROID_RECOVERY_REQUIRED_PATTERNS = [
  /(^|\/)BoardConfig.*\.mk$/i,
  /(^|\/)AndroidProducts\.mk$/i,
  /(^|\/).*fstab.*$/i,
];

const ANDROID_RECOVERY_VARIABLES = [
  'TARGET_BOARD_PLATFORM',
  'PRODUCT_PLATFORM',
  'PRODUCT_DEVICE',
  'PRODUCT_MODEL',
  'PRODUCT_NAME',
  'TARGET_DEVICE',
  'TARGET_OTA_ASSERT_DEVICE',
  'TARGET_BOOTLOADER_BOARD_NAME',
  'TARGET_RECOVERY_PIXEL_FORMAT',
  'BOARD_BOOT_HEADER_VERSION',
  'BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE',
  'BOARD_KERNEL_CMDLINE',
  'BOARD_KERNEL_BASE',
  'BOARD_KERNEL_PAGESIZE',
  'BOARD_MKBOOTIMG_ARGS',
  'BOARD_BOOTIMAGE_PARTITION_SIZE',
  'BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE',
  'BOARD_RECOVERYIMAGE_PARTITION_SIZE',
  'BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE',
  'TARGET_RECOVERY_FSTAB',
  'TW_THEME',
  'OF_SCREEN_H',
  'OF_SCREEN_W',
  'OF_TOUCH_*',
  'TW_INCLUDE_CRYPTO',
  'TW_INCLUDE_CRYPTO_FBE',
  'PRODUCT_COPY_FILES',
];

const ANDROID_VALIDATION_COMMANDS = [
  'find {{projectRoot}} -name BoardConfig.mk -o -name AndroidProducts.mk -o -name "*fstab*"',
  'grep -RIn "TARGET_BOARD_PLATFORM\\|PRODUCT_PLATFORM\\|PRODUCT_DEVICE\\|BOARD_RECOVERYIMAGE_PARTITION_SIZE\\|BOARD_BOOT_HEADER_VERSION" {{projectRoot}}',
  'grep -RIn "keymaster\\|keymint\\|gatekeeper\\|decrypt\\|vbmeta\\|avb\\|fstab" {{projectRoot}}',
];

const GAME_RUNTIME_PATTERNS = [
  /(^|\/)README(\..*)?$/i,
  /(^|\/).*config\.(ini|cfg|conf|json|toml|ya?ml)$/i,
  /(^|\/).*t7patch.*$/i,
  /(^|\/).*bo3.*$/i,
  /(^|\/).*blackops3.*$/i,
  /(^|\/)steam_appid\.txt$/i,
  /(^|\/).*dxvk.*$/i,
  /(^|\/).*vkd3d.*$/i,
  /(^|\/).*reshade.*$/i,
  /(^|\/).*specialk.*$/i,
  /(^|\/).*3dmigoto.*$/i,
  /(^|\/).*suwsf.*$/i,
  /(^|\/).*optiscaler.*$/i,
  /(^|\/)mods?(\/|$)/i,
  /(^|\/)plugins?(\/|$)/i,
  /(^|\/)players(\/|$)/i,
  /(^|\/)workshop(\/|$)/i,
];

const GAME_RUNTIME_VARIABLES = [
  'BlackOps3',
  'SteamAppId',
  'MaxFPS',
  'SmoothFramerate',
  'MaxFrameLatency',
  'BackbufferCount',
  'VideoMemory',
  'StreamMinResident',
  'RestrictGraphicsOptions',
  'com_maxfps',
  'WINEDLLOVERRIDES',
  'DXVK_*',
  'VKD3D_*',
  'VK_*',
];

const GAME_RUNTIME_VALIDATION_COMMANDS = [
  'find {{projectRoot}} -maxdepth 4 -type f | sort',
  'grep -RIn "BlackOps3\\|t7patch\\|BO3Enhanced\\|MaxFPS\\|SmoothFramerate\\|BackbufferCount\\|VideoMemory\\|StreamMinResident" {{projectRoot}}',
  'grep -RIn "dxvk\\|vkd3d\\|ReShade\\|SpecialK\\|3DMigoto\\|SUWSF\\|OptiScaler\\|VK_ICD_FILENAMES\\|VK_DRIVER_FILES" {{projectRoot}}',
  'grep -RIn "anti-cheat\\|anticheat\\|DRM\\|bypass\\|cheat\\|stealth\\|public match\\|ranked" {{projectRoot}}',
];

const RENDER_ENHANCEMENT_VARIABLES = [
  'PresentHook',
  'ResizeBuffersHook',
  'SwapChainFormat',
  'TargetFrameTimeMs',
  'FramerateLimit',
  'WaitableSwapChain',
  'LowLatencyMode',
  'HDRMode',
  'HDRColorSpace',
  'TextureInjection',
  'ReplacementManifest',
  'APITranslation',
  'DXGI_*',
  'D3D11_*',
];

const RENDER_ENHANCEMENT_VALIDATION_COMMANDS = [
  'grep -RIn "IDXGISwapChain\\|Present1\\|Present\\|ResizeBuffers\\|CreateSwapChain\\|D3D11CreateDevice\\|DXGI_SWAP_CHAIN" {{projectRoot}}',
  'grep -RIn "TargetFrameTimeMs\\|FramerateLimit\\|WaitableSwapChain\\|LowLatencyMode\\|frametime\\|frame pacing\\|latency" {{projectRoot}}',
  'grep -RIn "TextureInjection\\|ReplacementManifest\\|DDS\\|BC7\\|mipmap\\|sRGB\\|CreateTexture2D\\|PSSetShaderResources" {{projectRoot}}',
  'grep -RIn "HDR10\\|scRGB\\|PQ\\|Rec2020\\|DXGI_COLOR_SPACE\\|SetHDRMetaData\\|R10G10B10A2" {{projectRoot}}',
  'grep -RIn "DXVK\\|VKD3D\\|D3D11On12\\|Vulkan\\|Wine\\|Proton\\|box64\\|Adreno\\|Turnip\\|Mesa\\|RM11Pro\\|Red Magic" {{projectRoot}}',
];

export const PROFILES = {
  generic_source_tree: {
    id: 'generic_source_tree',
    label: 'Generic source tree',
    importantFilePatterns: [
      /(^|\/)README(\..*)?$/i,
      /(^|\/)package\.json$/i,
      /(^|\/)Makefile$/i,
      /(^|\/).*\.mk$/i,
      /(^|\/).*\.toml$/i,
      /(^|\/).*\.ya?ml$/i,
      /(^|\/).*\.json$/i,
    ],
    requiredFilePatterns: [],
    importantVariables: [],
    riskyLeftovers: ['sample', 'example', 'template', 'dummy', 'fake', 'placeholder'],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'duplicated definitions with different values',
      'referenced paths not present in the scanned tree',
      'TODO/FIXME markers in important files',
    ],
    validationCommands: [
      'find {{projectRoot}} -maxdepth 3 -type f | sort | head -200',
      'grep -RIn "TODO\\|FIXME\\|PLACEHOLDER\\|STUB" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  android_recovery: {
    id: 'android_recovery',
    label: 'Android recovery device tree',
    importantFilePatterns: ANDROID_RECOVERY_PATTERNS,
    requiredFilePatterns: ANDROID_RECOVERY_REQUIRED_PATTERNS,
    importantVariables: ANDROID_RECOVERY_VARIABLES,
    riskyLeftovers: [
      'RM10Pro',
      'RM10',
      'sm8750',
      'kalama',
      'lahaina',
      'kona',
      'taro',
      'pineapple',
      'waipio',
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
    ],
    expectedDirectoryPatterns: [
      /(^|\/)recovery\/root(\/|$)/i,
      /(^|\/)vendor(\/|$)/i,
      /(^|\/)proprietary(\/|$)/i,
    ],
    commonContradictions: [
      'TARGET_BOARD_PLATFORM mismatch',
      'PRODUCT_PLATFORM mismatch',
      'codename mismatch',
      'partition size mismatch',
      'recovery image size mismatch',
      'boot header version mismatch',
      'wrong SoC family leftovers',
      'init rc service binary missing',
      'fstab references partition or mount options not supported by known-good facts',
      'AVB/vbmeta assumptions conflict with observed device facts',
    ],
    validationCommands: ANDROID_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  orangefox: {
    id: 'orangefox',
    label: 'OrangeFox recovery tree',
    extends: 'android_recovery',
    importantFilePatterns: [
      ...ANDROID_RECOVERY_PATTERNS,
      /(^|\/).*orangefox.*$/i,
      /(^|\/)vendorsetup\.sh$/i,
    ],
    importantVariables: [
      ...ANDROID_RECOVERY_VARIABLES,
      'FOX_*',
      'OF_*',
      'TW_*',
    ],
    riskyLeftovers: ['twrp-only', 'oldfox', 'RM10Pro', 'sm8750', 'template', 'placeholder'],
    validationCommands: [
      ...ANDROID_VALIDATION_COMMANDS,
      'grep -RIn "FOX_\\|OF_\\|TW_" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  twrp: {
    id: 'twrp',
    label: 'TWRP recovery tree',
    extends: 'android_recovery',
    importantFilePatterns: ANDROID_RECOVERY_PATTERNS,
    importantVariables: [
      ...ANDROID_RECOVERY_VARIABLES,
      'TW_*',
    ],
    riskyLeftovers: ['orangefox-only', 'RM10Pro', 'sm8750', 'template', 'placeholder'],
    validationCommands: [
      ...ANDROID_VALIDATION_COMMANDS,
      'grep -RIn "TW_" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  android_kernel: {
    id: 'android_kernel',
    label: 'Android kernel tree',
    importantFilePatterns: [
      /(^|\/)Makefile$/i,
      /(^|\/)Kconfig$/i,
      /(^|\/)arch\/arm64\/configs\/.*defconfig$/i,
      /(^|\/)arch\/arm64\/boot\/dts\/.*\.dtsi?$/i,
    ],
    importantVariables: ['CONFIG_*', 'ARCH', 'CROSS_COMPILE', 'KERNELRELEASE'],
    riskyLeftovers: ['TODO', 'FIXME', 'PLACEHOLDER', 'STUB', 'deprecated'],
    expectedDirectoryPatterns: [/^arch\/arm64\//i, /^drivers\//i],
    commonContradictions: [
      'defconfig enables feature but driver path is absent',
      'DTS compatible strings conflict with target SoC',
    ],
    validationCommands: [
      'find {{projectRoot}} -path "*/arch/arm64/configs/*defconfig" -o -path "*/arch/arm64/boot/dts/*"',
      'grep -RIn "CONFIG_\\|compatible =" {{projectRoot}}/arch {{projectRoot}}/drivers',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  gki_kernel: {
    id: 'gki_kernel',
    label: 'GKI kernel tree',
    extends: 'android_kernel',
    importantFilePatterns: [
      /(^|\/)BUILD\.bazel$/i,
      /(^|\/)build\.config.*$/i,
      /(^|\/)common\/.*$/i,
      /(^|\/)modules\.load.*$/i,
    ],
    importantVariables: ['CONFIG_*', 'KMI_*', 'ABI_*'],
    riskyLeftovers: ['non-gki', 'vendor hack', 'TODO', 'FIXME'],
    validationCommands: [
      'find {{projectRoot}} -name "build.config*" -o -name "modules.load*" -o -name "abi_*"',
      'grep -RIn "KMI\\|ABI\\|CONFIG_" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  userspace_graphics: {
    id: 'userspace_graphics',
    label: 'Userspace graphics stack',
    importantFilePatterns: [
      /(^|\/)meson\.build$/i,
      /(^|\/)CMakeLists\.txt$/i,
      /(^|\/).*wayland.*$/i,
      /(^|\/).*xwayland.*$/i,
      /(^|\/).*glx.*$/i,
      /(^|\/).*egl.*$/i,
      /(^|\/).*vulkan.*$/i,
      /(^|\/).*drm.*$/i,
    ],
    importantVariables: ['LD_LIBRARY_PATH', 'VK_*', 'MESA_*', 'DISPLAY', 'WAYLAND_DISPLAY', 'XDG_RUNTIME_DIR'],
    riskyLeftovers: ['llvmpipe', 'swrast', 'software', 'stub', 'placeholder'],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'GLX/EGL configuration references libraries not present',
      'Wayland socket variables disagree across launch scripts',
      'software renderer fallback present in hardware-rendering lane',
    ],
    validationCommands: [
      'grep -RIn "GLX\\|EGL\\|Vulkan\\|VK_\\|LD_LIBRARY_PATH\\|WAYLAND_DISPLAY\\|DISPLAY" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  linux_container: {
    id: 'linux_container',
    label: 'Linux container runtime',
    importantFilePatterns: [
      /(^|\/)Dockerfile$/i,
      /(^|\/).*container.*$/i,
      /(^|\/).*rootfs.*$/i,
      /(^|\/).*chroot.*$/i,
      /(^|\/).*proot.*$/i,
      /(^|\/).*systemd.*$/i,
    ],
    importantVariables: ['PATH', 'LD_LIBRARY_PATH', 'HOME', 'USER', 'XDG_RUNTIME_DIR'],
    riskyLeftovers: ['host-only', 'placeholder', 'fake', 'stub'],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'host path leaked into container config',
      'rootfs path referenced but absent',
      'service binary referenced but absent',
    ],
    validationCommands: [
      'grep -RIn "rootfs\\|chroot\\|proot\\|LD_LIBRARY_PATH\\|XDG_RUNTIME_DIR" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  gamescope: {
    id: 'gamescope',
    label: 'Gamescope / wlroots graphics stack',
    extends: 'userspace_graphics',
    importantFilePatterns: [
      /(^|\/).*gamescope.*$/i,
      /(^|\/).*wlroots.*$/i,
      /(^|\/).*xwayland.*$/i,
      /(^|\/).*wayland.*$/i,
      /(^|\/).*drm.*$/i,
      /(^|\/).*xkb.*$/i,
    ],
    importantVariables: ['GAMESCOPE_*', 'WAYLAND_DISPLAY', 'DISPLAY', 'XWAYLAND_*', 'XKB_*', 'LD_LIBRARY_PATH'],
    riskyLeftovers: ['swrast', 'llvmpipe', 'placeholder', 'stub', 'drm lease'],
    validationCommands: [
      'grep -RIn "gamescope\\|wlroots\\|Xwayland\\|GLX\\|xkb\\|WAYLAND_DISPLAY\\|DISPLAY" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  game_modding: {
    id: 'game_modding',
    label: 'Game modding runtime',
    runtimeProfile: true,
    importantFilePatterns: GAME_RUNTIME_PATTERNS,
    requiredFilePatterns: [],
    importantVariables: GAME_RUNTIME_VARIABLES,
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'bypass',
      'anti-cheat',
      'anticheat',
      'Arxan',
      'public match',
      'ranked',
      'stealth',
    ],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'runtime target identity is ambiguous',
      'wrapper DLL chain is present but not documented',
      'graphics loader variables point at missing or incompatible drivers',
      'performance config values disagree across launch profiles',
      'security or exploit-mitigation notes are present without validation evidence',
      'anti-cheat, DRM, public-match, or ownership-evasion terms require a hard safety review',
    ],
    validationCommands: GAME_RUNTIME_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  graphics_wrapper: {
    id: 'graphics_wrapper',
    label: 'Graphics wrapper and injection chain',
    extends: 'game_modding',
    importantFilePatterns: [
      ...GAME_RUNTIME_PATTERNS,
      /(^|\/).*d3d.*$/i,
      /(^|\/).*dxgi.*$/i,
      /(^|\/).*vulkan.*$/i,
      /(^|\/).*shader.*$/i,
    ],
    importantVariables: [
      ...GAME_RUNTIME_VARIABLES,
      'DXVK_*',
      'VKD3D_*',
      'MESA_*',
      'PROTON_*',
      'WINEDLLOVERRIDES',
    ],
    riskyLeftovers: ['stub', 'placeholder', 'software renderer', 'swrast', 'llvmpipe', 'bypass'],
    validationCommands: [
      'grep -RIn "dxvk\\|vkd3d\\|d3d11\\|dxgi\\|dinput8\\|winmm\\|version.dll\\|ReShade\\|SpecialK\\|3DMigoto\\|SUWSF\\|OptiScaler" {{projectRoot}}',
      'grep -RIn "WINEDLLOVERRIDES\\|VK_ICD_FILENAMES\\|VK_DRIVER_FILES\\|VK_LOADER_DEBUG\\|MESA_\\|PROTON_" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  vulkan_loader: {
    id: 'vulkan_loader',
    label: 'Vulkan loader and ICD runtime',
    runtimeProfile: true,
    importantFilePatterns: [
      /(^|\/).*vulkan.*$/i,
      /(^|\/).*icd.*\.json$/i,
      /(^|\/).*dxvk.*$/i,
      /(^|\/).*vkd3d.*$/i,
      /(^|\/).*loader.*$/i,
      /(^|\/).*gpu.*$/i,
      /(^|\/).*mesa.*$/i,
    ],
    requiredFilePatterns: [],
    importantVariables: ['VK_ICD_FILENAMES', 'VK_DRIVER_FILES', 'VK_LOADER_DEBUG', 'VK_INSTANCE_LAYERS', 'MESA_*', 'DXVK_*', 'VKD3D_*'],
    riskyLeftovers: ['llvmpipe', 'swrast', 'software', 'ERROR_INCOMPATIBLE_DRIVER', 'placeholder', 'stub'],
    expectedDirectoryPatterns: [],
    commonContradictions: [
      'ICD JSON references a missing library',
      'loader debug output reports incompatible driver negotiation',
      'runtime variables select different Vulkan drivers',
      'software renderer fallback appears in a hardware-rendering lane',
    ],
    validationCommands: [
      'grep -RIn "VK_ICD_FILENAMES\\|VK_DRIVER_FILES\\|VK_LOADER_DEBUG\\|VK_INSTANCE_LAYERS\\|vk_icdNegotiateLoaderICDInterfaceVersion\\|ERROR_INCOMPATIBLE_DRIVER\\|ICD.library_path\\|api_version" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
  bo3_zombies_diagnostics: {
    id: 'bo3_zombies_diagnostics',
    label: 'Black Ops 3 Zombies diagnostics',
    extends: 'game_modding',
    importantFilePatterns: [
      ...GAME_RUNTIME_PATTERNS,
      /(^|\/).*zombies?.*$/i,
      /(^|\/).*workshop.*$/i,
      /(^|\/).*t7.*$/i,
      /(^|\/).*players\/config\.ini$/i,
    ],
    importantVariables: [
      ...GAME_RUNTIME_VARIABLES,
      'network_password',
      'lobby_password',
      'friends_only',
    ],
    riskyLeftovers: [
      'TODO',
      'FIXME',
      'PLACEHOLDER',
      'STUB',
      'anti-cheat',
      'anticheat',
      'Arxan',
      'bypass',
      'cheat menu',
      'trainer',
      'stealth injection',
      'public match',
      'ranked',
      'unlock all',
      'ban evasion',
      'ownership verification',
    ],
    commonContradictions: [
      'BO3 runtime identity or Steam AppID is ambiguous',
      'Zombies/private co-op security settings are present without validation notes',
      'performance config values disagree across profiles',
      'wrapper DLL chain is present without explicit load-order evidence',
      'anti-cheat, DRM, public-match, or ownership-evasion terms require a hard safety review',
    ],
    validationCommands: GAME_RUNTIME_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  render_enhancement_plugin: {
    id: 'render_enhancement_plugin',
    label: 'Render enhancement plugin',
    extends: 'graphics_wrapper',
    importantFilePatterns: [
      ...GAME_RUNTIME_PATTERNS,
      /(^|\/).*specialk.*$/i,
      /(^|\/).*render.*$/i,
      /(^|\/).*swapchain.*$/i,
      /(^|\/).*frame.*$/i,
      /(^|\/).*hdr.*$/i,
      /(^|\/).*texture.*$/i,
      /(^|\/).*manifest.*\.(json|toml|ya?ml|ini|cfg|conf|txt)$/i,
      /(^|\/).*plugins?(\/|$)/i,
    ],
    importantVariables: [
      ...GAME_RUNTIME_VARIABLES,
      ...RENDER_ENHANCEMENT_VARIABLES,
    ],
    riskyLeftovers: ['stub', 'placeholder', 'software renderer', 'swrast', 'llvmpipe', 'bypass', 'stealth'],
    commonContradictions: [
      'render hook target is ambiguous',
      'frame limiter target conflicts with game config',
      'texture replacement manifest is referenced but absent',
      'HDR color space or swapchain format is declared without validation evidence',
      'API translation path differs across Windows, Wine, Proton, or mobile Linux profiles',
    ],
    validationCommands: RENDER_ENHANCEMENT_VALIDATION_COMMANDS,
    reportSections: COMMON_REPORT_SECTIONS,
  },
  rm11pro_gaming_runtime: {
    id: 'rm11pro_gaming_runtime',
    label: 'Red Magic 11 Pro gaming runtime',
    extends: 'render_enhancement_plugin',
    importantFilePatterns: [
      ...GAME_RUNTIME_PATTERNS,
      /(^|\/).*rm11pro.*$/i,
      /(^|\/).*red[-_ ]?magic.*$/i,
      /(^|\/).*adreno.*$/i,
      /(^|\/).*turnip.*$/i,
      /(^|\/).*mesa.*$/i,
      /(^|\/).*box64.*$/i,
      /(^|\/).*wine.*$/i,
      /(^|\/).*proot.*$/i,
      /(^|\/).*termux.*$/i,
      /(^|\/).*winlator.*$/i,
    ],
    importantVariables: [
      ...GAME_RUNTIME_VARIABLES,
      ...RENDER_ENHANCEMENT_VARIABLES,
      'MESA_*',
      'TU_*',
      'BOX64_*',
      'WINE_*',
      'PROOT_*',
      'TERMUX_*',
      'VK_DRIVER_FILES',
      'VK_ICD_FILENAMES',
    ],
    riskyLeftovers: ['llvmpipe', 'swrast', 'software renderer', 'placeholder', 'stub', 'host-only'],
    commonContradictions: [
      'RM11Pro runtime identity is ambiguous',
      'Adreno or Turnip driver selection conflicts with Vulkan loader evidence',
      'box64, Wine, or container variables disagree across launch profiles',
      'desktop render settings are reused without mobile validation evidence',
    ],
    validationCommands: [
      ...RENDER_ENHANCEMENT_VALIDATION_COMMANDS,
      'grep -RIn "RM11Pro\\|Red Magic\\|Adreno\\|Turnip\\|Mesa\\|box64\\|Wine\\|proot\\|Termux\\|Winlator\\|VK_DRIVER_FILES\\|VK_ICD_FILENAMES" {{projectRoot}}',
    ],
    reportSections: COMMON_REPORT_SECTIONS,
  },
};

export function getProfile(profileId = 'generic_source_tree') {
  return resolveProfile(profileId);
}

function resolveProfile(profileId, seen = new Set()) {
  const profile = PROFILES[profileId];
  if (!profile) {
    const known = Object.keys(PROFILES).sort().join(', ');
    throw new Error(`Unknown scan profile "${profileId}". Known profiles: ${known}`);
  }
  if (seen.has(profileId)) {
    throw new Error(`Profile inheritance cycle detected at "${profileId}".`);
  }

  if (!profile.extends) {
    return profile;
  }

  const parent = resolveProfile(profile.extends, new Set([...seen, profileId]));
  return {
    ...parent,
    ...profile,
    importantFilePatterns: profile.importantFilePatterns ?? parent.importantFilePatterns,
    requiredFilePatterns: profile.requiredFilePatterns ?? parent.requiredFilePatterns,
    importantVariables: profile.importantVariables ?? parent.importantVariables,
    riskyLeftovers: profile.riskyLeftovers ?? parent.riskyLeftovers,
    validationCommands: profile.validationCommands ?? parent.validationCommands,
    reportSections: profile.reportSections ?? parent.reportSections,
  };
}

export function listProfiles() {
  return Object.values(PROFILES).map(profile => ({
    id: profile.id,
    label: profile.label,
  }));
}
